# Generated by Django 4.0.5 on 2022-07-06 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_info', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('data', models.FileField(upload_to='user_data')),
            ],
        ),
        migrations.CreateModel(
            name='Artikul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('title', models.TextField()),
                ('amount', models.CharField(max_length=25, null=True)),
                ('in_field', models.IntegerField(default=0)),
                ('tag', models.CharField(max_length=50)),
                ('boxes', models.FloatField()),
                ('packaging', models.CharField(blank=True, max_length=50)),
                ('sector', models.CharField(max_length=15)),
                ('comment', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('truck', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='prijemka.truck')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
