# Generated by Django 4.0.5 on 2022-07-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prijemka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikul',
            old_name='truck',
            new_name='truck_info',
        ),
    ]
