# Generated by Django 4.0.5 on 2022-07-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('lead', models.CharField(default='Краткое описание продукта', max_length=100)),
                ('description', models.TextField()),
                ('app_name', models.CharField(default='Ссылка на страницу приложения', max_length=30)),
            ],
        ),
    ]
